"""The Tribonema phase: manifest validation, design checks, and statistics.

Every dataset here is synthetic and generated by the test suite. It exists to
prove the analysis behaves correctly — that it finds a planted dose response and,
just as importantly, that it does not invent one when there is none.
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path

import numpy as np
import pytest
from conftest import build_synthetic_experiment

from tribovision.treatment import (
    TreatmentDataError,
    benjamini_hochberg,
    fit_dose_response,
    four_parameter_logistic,
    leave_one_day_out,
    load_treatment_manifest,
    run_treatment_analysis,
    stratified_spearman,
    write_template,
)


def test_template_lists_every_required_column(tmp_path: Path) -> None:
    path = write_template(tmp_path / "template.csv")
    with path.open(newline="", encoding="utf-8") as handle:
        header = next(csv.reader(handle))
    for column in (
        "experiment_day",
        "plate_id",
        "well_id",
        "concentration_ug_per_ml",
        "exposure_hours",
        "control_type",
        "replicate",
    ):
        assert column in header


def test_a_manifest_missing_required_columns_is_rejected(tmp_path: Path) -> None:
    path = tmp_path / "bad.csv"
    path.write_text("image_path,treatment\nx.png,extract\n", encoding="utf-8")
    with pytest.raises(TreatmentDataError, match="missing required column"):
        load_treatment_manifest(path)


def test_a_design_without_controls_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, concentrations=(25.0, 50.0, 100.0))
    with pytest.raises(TreatmentDataError, match="no zero-concentration control"):
        load_treatment_manifest(manifest)


def test_a_design_with_one_concentration_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, concentrations=(0.0,))
    with pytest.raises(TreatmentDataError, match="only one concentration"):
        load_treatment_manifest(manifest)


def test_a_design_without_replicate_wells_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, days=("2026-03-01",), wells_per_condition=1)
    with pytest.raises(TreatmentDataError, match="fewer than two independent wells"):
        load_treatment_manifest(manifest)


def test_a_sound_design_loads(tmp_path: Path) -> None:
    records = load_treatment_manifest(build_synthetic_experiment(tmp_path))
    assert len(records) == 2 * 5 * 2 * 2
    assert {record.experiment_day for record in records} == {"2026-03-01", "2026-03-08"}


def test_viability_is_derived_from_absorbance_when_not_given(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, days=("d1", "d2"))
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row["viability_fraction"] = ""
        row["mts_absorbance"] = "0.8"
        row["mts_blank_absorbance"] = "0.1"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    records = load_treatment_manifest(manifest)
    assert records[0].viability_fraction == pytest.approx(0.7)


def test_image_paths_cannot_escape_the_manifest_directory(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    rows[0]["image_path"] = "../../../etc/passwd"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    with pytest.raises(TreatmentDataError, match="escapes the manifest directory"):
        load_treatment_manifest(manifest)


def test_benjamini_hochberg_matches_a_worked_example() -> None:
    q = benjamini_hochberg([0.01, 0.02, 0.03, 0.04, 0.05])
    assert q == pytest.approx([0.05, 0.05, 0.05, 0.05, 0.05])
    assert benjamini_hochberg([]) == []
    # Correction can only make a p-value larger.
    raw = [0.001, 0.5, 0.9]
    assert all(a >= b for a, b in zip(benjamini_hochberg(raw), raw, strict=True))


def test_benjamini_hochberg_enforces_monotonicity() -> None:
    """Without the running minimum, a later q-value can drop below an earlier one.

    For p = [0.01, 0.04, 0.03] the rank-scaled values in sorted order are
    [0.03, 0.045, 0.04]. Without the step-up minimum the middle one stays at
    0.045, so the *smaller* p-value 0.03 would receive a larger q-value than the
    larger p-value 0.04 — an ordering violation that makes the correction
    incoherent. The correct answer pulls it down to 0.04.
    """
    assert benjamini_hochberg([0.01, 0.04, 0.03]) == pytest.approx([0.03, 0.04, 0.04])
    q = benjamini_hochberg([0.001, 0.9, 0.02, 0.5, 0.03])
    ordered = [q[index] for index in np.argsort([0.001, 0.9, 0.02, 0.5, 0.03])]
    assert all(a <= b + 1e-12 for a, b in zip(ordered, ordered[1:], strict=False))


def test_benjamini_hochberg_survives_a_non_finite_p_value() -> None:
    """One undefined test used to turn every q-value in the family into NaN."""
    q = benjamini_hochberg([0.001, float("nan"), 0.5])
    assert math.isnan(q[1])
    assert q[0] == pytest.approx(0.002) and q[2] == pytest.approx(0.5)


def test_dose_response_fit_recovers_a_known_ic50() -> None:
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 3, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    fit = fit_dose_response(concentrations, responses)
    assert fit["fitted"]
    assert fit["ic50_ug_per_ml"] == pytest.approx(30.0, rel=0.2)
    assert fit["r_squared"] > 0.99


@pytest.mark.parametrize(
    "concentrations",
    [
        # One concentration: nothing to fit.
        [0.0, 10.0, 10.0],
        # Four points, four parameters: zero residual degrees of freedom.
        [0.0, 1.0, 10.0, 100.0, 1000.0],
        # Five distinct concentrations but only 6 non-zero wells.
        [0.0, 1.0, 1.0, 3.0, 10.0, 30.0, 100.0],
    ],
)
def test_dose_response_refuses_a_design_that_cannot_constrain_four_parameters(
    concentrations: list[float],
) -> None:
    values = np.linspace(1.0, 0.2, len(concentrations))
    fit = fit_dose_response(np.array(concentrations), values)
    assert not fit["fitted"]
    assert "at least 5 distinct non-zero concentrations" in fit["reason"]


def test_dose_response_fits_once_the_design_is_adequate() -> None:
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 2, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    assert fit_dose_response(concentrations, responses)["fitted"]


def test_a_bootstrap_interval_is_withheld_when_resamples_do_not_converge() -> None:
    """A CI from only the well-behaved resamples is biased narrow, so report none."""
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 3, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    fit = fit_dose_response(concentrations, responses)
    assert 0.0 <= fit["bootstrap_convergence_rate"] <= 1.0
    if fit["bootstrap_convergence_rate"] < 0.8:
        assert fit["ic50_ci95"] is None
        assert "biased narrow" in fit["ic50_ci95_note"]
    else:
        assert fit["ic50_ci95"] is not None


def test_an_extrapolated_ic50_is_flagged() -> None:
    concentrations = np.array([1, 2, 3, 4, 5, 6] * 3, dtype=float)
    responses = np.linspace(1.0, 0.95, concentrations.size)
    fit = fit_dose_response(concentrations, responses)
    if fit["fitted"] and not fit["ic50_within_tested_range"]:
        assert "extrapolation" in fit["warning"]


def test_leave_one_day_out_needs_more_than_one_day() -> None:
    result = leave_one_day_out(np.zeros((4, 2)), np.zeros(4), ["d1"] * 4)
    assert not result["evaluated"]


def test_leave_one_day_out_finds_real_signal_and_rejects_noise() -> None:
    rng = np.random.default_rng(1)
    days = ["d1"] * 12 + ["d2"] * 12
    features = rng.normal(size=(24, 2))
    signal = 2.0 * features[:, 0] + rng.normal(0, 0.1, size=24)
    strong = leave_one_day_out(features, signal, days, permutations=200, seed=2)
    assert strong["r_squared"] > 0.8
    assert strong["permutation_p_value"] < 0.05

    noise = rng.normal(size=24)
    weak = leave_one_day_out(features, noise, days, permutations=200, seed=2)
    assert weak["permutation_p_value"] > 0.05


def test_end_to_end_analysis_detects_a_planted_dose_response(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "study", effect=True, seed=3)
    report = run_treatment_analysis(
        manifest, tmp_path / "out", instance_method="connected_components", min_area=5
    )

    assert report["segmenter"] == "classical-baseline"
    assert report["wells"] == 20
    assert report["experiment_days"] == ["2026-03-01", "2026-03-08"]
    area = report["dose_response"]["area_pixels_mean"]
    # Cells were made to shrink with dose.
    assert area["spearman_rho"] < -0.7
    assert area["q_value_bh"] < 0.05
    assert area["significant_at_q_0.05"]

    prediction = report["viability_linkage"]["prediction"]
    assert prediction["evaluated"]
    assert prediction["r_squared"] > 0.5
    assert prediction["permutation_p_value"] < 0.05

    assert (tmp_path / "out" / "treatment_report.json").is_file()
    assert (tmp_path / "out" / "well_level_summary.csv").is_file()
    assert (tmp_path / "out" / "treatment_morphology.csv").is_file()
    persisted = json.loads((tmp_path / "out" / "treatment_report.json").read_text())
    assert "does not establish a mechanism" in persisted["claim_boundary"]


def test_end_to_end_analysis_does_not_invent_a_dose_response(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "null", effect=False, seed=11)
    report = run_treatment_analysis(
        manifest, tmp_path / "out", instance_method="connected_components", min_area=5
    )
    area = report["dose_response"]["area_pixels_mean"]
    assert area["q_value_bh"] > 0.05
    assert not area["significant_at_q_0.05"]


def test_a_missing_image_is_reported_rather_than_silently_skipped(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "gap")
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    (tmp_path / "gap" / rows[0]["image_path"]).unlink()
    with pytest.raises(TreatmentDataError, match="is missing"):
        run_treatment_analysis(manifest, tmp_path / "out")


def test_the_well_is_the_unit_so_extra_fields_do_not_inflate_n(tmp_path: Path) -> None:
    few = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "a", fields=2, seed=5),
        tmp_path / "outa",
        instance_method="connected_components",
        min_area=5,
    )
    many = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "b", fields=6, seed=5),
        tmp_path / "outb",
        instance_method="connected_components",
        min_area=5,
    )
    assert few["wells"] == many["wells"]
    assert many["images_analysed"] == 3 * few["images_analysed"]


# --------------------------------------------------- design checks added later


def test_a_single_experiment_day_is_refused(tmp_path: Path) -> None:
    """Nothing can be validated on a day the model did not see."""
    manifest = build_synthetic_experiment(tmp_path, days=("2026-03-01",))
    with pytest.raises(TreatmentDataError, match="only one experiment day"):
        load_treatment_manifest(manifest)


def test_a_zero_dose_well_is_not_automatically_a_vehicle_control(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        if row["control_type"] == "vehicle":
            row["control_type"] = "untreated"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    with pytest.raises(TreatmentDataError, match="control_type='vehicle'"):
        load_treatment_manifest(manifest)


# ------------------------------------------------ leave-one-day-out correctness


def test_a_day_that_cannot_be_trained_against_is_not_scored_as_zero() -> None:
    """Skipped folds used to keep a prediction of 0.0 and enter R^2 as real."""
    features = np.random.default_rng(0).normal(size=(6, 2))
    targets = np.arange(6.0)
    result = leave_one_day_out(features, targets, ["a"] + ["b"] * 5, permutations=20)
    assert result["evaluated"] is False
    assert result["wells_skipped"] == 5
    assert "at least two wells on the other days" in result["reason"]


def test_within_day_r_squared_is_reported_next_to_the_plain_one() -> None:
    rng = np.random.default_rng(5)
    days = ["d1"] * 10 + ["d2"] * 10
    features = rng.normal(size=(20, 2))
    targets = 1.5 * features[:, 0] + rng.normal(0, 0.1, size=20)
    result = leave_one_day_out(features, targets, days, permutations=100, seed=1)
    assert result["evaluated"]
    assert "within_day_r_squared" in result
    assert result["wells_scored"] == 20 and result["wells_skipped"] == 0
    assert 0.0 <= result["r_squared_percentile_in_null"] <= 1.0
    assert "within_day_r_squared" in result["interpretation"]


def test_a_pure_between_day_difference_inflates_plain_r2_but_not_within_day_r2() -> None:
    """The whole point of reporting both numbers.

    Three days with evenly spaced batch offsets, and a feature that carries only
    the offset. Trained on two days, the model extrapolates the third day's level
    correctly, so R^2 against the global mean looks excellent — while explaining
    nothing at all about which well within a day has higher viability.
    """
    rng = np.random.default_rng(11)
    days = ["d1"] * 8 + ["d2"] * 8 + ["d3"] * 8
    offsets = np.array([0.0] * 8 + [5.0] * 8 + [10.0] * 8)
    features = np.column_stack([offsets + rng.normal(0, 0.02, 24), rng.normal(size=24)])
    targets = offsets + rng.normal(0, 0.3, 24)
    result = leave_one_day_out(features, targets, days, permutations=50, seed=3)
    assert result["evaluated"]
    # Between-day structure alone explains nearly all variance around the global mean...
    assert result["r_squared"] > 0.9
    # ...and essentially none of the variance within a day.
    assert result["within_day_r_squared"] < 0.5
    assert result["within_day_r_squared"] < result["r_squared"]


# ------------------------------------------------- day-stratified dose response


def test_a_pure_day_effect_is_not_reported_as_a_dose_effect() -> None:
    """Concentration confounded with day: the pooled test is fooled, the blocked one is not."""
    days = np.array(["d1"] * 8 + ["d2"] * 8)
    # Day 1 received only low doses, day 2 only high doses.
    concentrations = np.array([0, 0, 10, 10, 20, 20, 30, 30] * 2, dtype=float)
    concentrations[8:] += 100
    values = np.where(days == "d1", 1.0, 3.0) + np.random.default_rng(0).normal(0, 0.01, 16)
    result = stratified_spearman(concentrations, values, days, permutations=500, seed=1)
    assert result["p_value"] < 0.01  # pooled: looks like a strong dose response
    assert result["p_value_day_stratified"] > 0.05  # blocked: it was the day


def test_a_real_within_day_dose_effect_survives_blocking() -> None:
    days = np.array(["d1"] * 10 + ["d2"] * 10)
    concentrations = np.array([0, 10, 20, 30, 40] * 4, dtype=float)
    values = -0.05 * concentrations + np.where(days == "d1", 0.0, 2.0)
    result = stratified_spearman(concentrations, values, days, permutations=500, seed=1)
    assert result["spearman_rho"] < -0.5
    assert result["p_value_day_stratified"] < 0.05


# -------------------------------------------------- confirmatory vs exploratory


def test_features_are_labelled_by_what_they_actually_measure(tmp_path: Path) -> None:
    report = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "s", seed=3),
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=200,
    )
    kinds = report["feature_kinds"]
    assert kinds["total_area_pixels"] == "density"
    assert kinds["area_pixels_mean"] == "density-contaminated"
    assert kinds["circularity_mean"] == "shape"
    assert "fewer cells at higher dose" in report["confluency_caveat"]
    for name, entry in report["dose_response"].items():
        assert entry["feature_kind"] == kinds.get(name, entry["feature_kind"])


def test_the_confirmatory_endpoint_is_tested_separately_from_the_exploratory_model(
    tmp_path: Path,
) -> None:
    report = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "s", seed=3),
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=200,
    )
    linkage = report["viability_linkage"]
    assert "confirmatory_prediction" in linkage
    assert "exploratory_prediction" in linkage
    confirmatory = linkage["confirmatory_prediction"]
    assert confirmatory["feature"] == report["primary_feature"]
    # The pre-specified endpoint must be a shape feature, not a confluency proxy.
    assert report["feature_kinds"].get(report["primary_feature"]) == "shape"


def test_within_day_centring_is_on_by_default_and_narrows_the_claim() -> None:
    rng = np.random.default_rng(9)
    days = ["d1"] * 10 + ["d2"] * 10
    features = rng.normal(size=(20, 1))
    targets = 0.8 * features[:, 0] + rng.normal(0, 0.2, 20)
    result = leave_one_day_out(features, targets, days, permutations=100, seed=1)
    assert result["centred_by_day"] is True
    assert "relative to its own experiment day" in result["claim"]

    uncentred = leave_one_day_out(
        features, targets, days, permutations=100, seed=1, centre_by_day=False
    )
    assert uncentred["centred_by_day"] is False
    assert "confound" in uncentred["claim"]


def _null_confounded_experiment(seed: int, correlation: float) -> tuple:
    """Three days; morphology and viability each carry an unrelated day-level shift."""
    rng = np.random.default_rng(seed)
    days: list[str] = []
    feature: list[np.ndarray] = []
    viability: list[np.ndarray] = []
    for index in range(3):
        morphology_shift = rng.normal(0, 1.0)
        viability_shift = rng.normal(0, 0.3)
        latent = rng.normal(size=10)
        noise = rng.normal(size=10)
        days += [f"d{index}"] * 10
        feature.append(latent + morphology_shift)
        viability.append(
            0.2 * (correlation * latent + np.sqrt(1 - correlation**2) * noise)
            + viability_shift
            + 0.6
        )
    return np.concatenate(feature)[:, None], np.concatenate(viability), days


def test_centring_detects_effects_that_confounded_day_shifts_would_otherwise_hide() -> None:
    """The measured reason centring is the default.

    A model fitted across days learns a slope corrupted by day-level shifts that
    are independent in morphology and in viability. Fitted to within-day
    deviations it does not. Counted over several independent experiments at a
    moderate effect size, centring detects strictly more of them.
    """
    centred_hits = 0
    uncentred_hits = 0
    for trial in range(6):
        features, targets, days = _null_confounded_experiment(trial, correlation=0.5)
        centred = leave_one_day_out(features, targets, days, permutations=150, seed=trial)
        uncentred = leave_one_day_out(
            features, targets, days, permutations=150, seed=trial, centre_by_day=False
        )
        centred_hits += centred["permutation_p_value"] < 0.05
        uncentred_hits += uncentred["permutation_p_value"] < 0.05
    assert centred_hits > uncentred_hits


def test_centring_does_not_inflate_the_false_positive_rate() -> None:
    """Power is worthless if it comes from a broken null. Ten independent nulls."""
    significant = 0
    for trial in range(10):
        rng = np.random.default_rng(100 + trial)
        days: list[str] = []
        feature: list[np.ndarray] = []
        viability: list[np.ndarray] = []
        for index in range(3):
            days += [f"d{index}"] * 10
            feature.append(rng.normal(size=10) + rng.normal(0, 1.0))
            viability.append(rng.normal(0, 0.2, 10) + rng.normal(0, 0.3) + 0.6)
        result = leave_one_day_out(
            np.concatenate(feature)[:, None],
            np.concatenate(viability),
            days,
            permutations=200,
            seed=trial,
        )
        significant += result["permutation_p_value"] < 0.05
    # At alpha = 0.05 over 10 pure nulls, more than two hits would be alarming.
    assert significant <= 2
