"""The Tribonema phase: manifest validation, design checks, and statistics.

Every dataset here is synthetic and generated by the test suite. It exists to
prove the analysis behaves correctly — that it finds a planted dose response and,
just as importantly, that it does not invent one when there is none.
"""

from __future__ import annotations

import csv
import json
import math
import shutil
from pathlib import Path

import numpy as np
import pytest
from conftest import build_synthetic_experiment
from PIL import Image

from tribovision.treatment import (
    REQUIRED_COLUMNS,
    TreatmentDataError,
    _dose_response_for,
    benjamini_hochberg,
    exponential_approach,
    fit_dose_response,
    fit_kinetics,
    four_parameter_logistic,
    leave_one_day_out,
    load_treatment_manifest,
    plan_experiment,
    run_treatment_analysis,
    stratified_spearman,
    write_template,
)


def test_template_lists_every_required_column(tmp_path: Path) -> None:
    path = write_template(tmp_path / "template.csv")
    with path.open(newline="", encoding="utf-8") as handle:
        header = next(csv.reader(handle))
    for column in (
        "experiment_day",
        "plate_id",
        "well_id",
        "concentration_ug_per_ml",
        "exposure_hours",
        "control_type",
        "replicate",
    ):
        assert column in header


def test_a_manifest_missing_required_columns_is_rejected(tmp_path: Path) -> None:
    path = tmp_path / "bad.csv"
    path.write_text("image_path,treatment\nx.png,extract\n", encoding="utf-8")
    with pytest.raises(TreatmentDataError, match="missing required column"):
        load_treatment_manifest(path)


def test_a_design_without_controls_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, concentrations=(25.0, 50.0, 100.0))
    with pytest.raises(TreatmentDataError, match="no zero-concentration control"):
        load_treatment_manifest(manifest)


def test_a_design_with_one_concentration_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, concentrations=(0.0,))
    with pytest.raises(TreatmentDataError, match="only one concentration"):
        load_treatment_manifest(manifest)


def test_a_design_without_replicate_wells_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, days=("2026-03-01",), wells_per_condition=1)
    with pytest.raises(TreatmentDataError, match="fewer than two independent wells"):
        load_treatment_manifest(manifest)


def test_a_sound_design_loads(tmp_path: Path) -> None:
    records = load_treatment_manifest(build_synthetic_experiment(tmp_path))
    assert len(records) == 2 * 5 * 2 * 2
    assert {record.experiment_day for record in records} == {"2026-03-01", "2026-03-08"}


def test_raw_mts_is_blank_corrected_and_normalised_to_vehicle(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, days=("d1", "d2"))
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row["viability_fraction"] = ""
        row["mts_absorbance"] = "0.8" if row["concentration_ug_per_ml"] == "0.0" else "0.45"
        row["mts_blank_absorbance"] = "0.1"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    records = load_treatment_manifest(manifest)
    vehicle = next(record for record in records if record.concentration_ug_per_ml == 0)
    treated = next(record for record in records if record.concentration_ug_per_ml > 0)
    assert vehicle.viability_fraction == pytest.approx(1.0)
    assert treated.viability_fraction == pytest.approx(0.5)
    assert treated.viability_source == "mts_normalized_to_vehicle"


def test_raw_mts_requires_a_blank_and_one_endpoint_per_well(tmp_path: Path) -> None:
    missing_blank = build_synthetic_experiment(tmp_path / "blank")
    with missing_blank.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row["viability_fraction"] = ""
        row["mts_absorbance"] = "0.8"
        row["mts_blank_absorbance"] = ""
    _write_rows(missing_blank, rows)
    with pytest.raises(TreatmentDataError, match="mts_blank_absorbance is required"):
        load_treatment_manifest(missing_blank)

    repeated = build_synthetic_experiment(
        tmp_path / "repeated", timepoints=(12.0, 24.0), longitudinal=True
    )
    with repeated.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row["viability_fraction"] = ""
        row["mts_absorbance"] = "0.8"
        row["mts_blank_absorbance"] = "0.1"
    _write_rows(repeated, rows)
    with pytest.raises(TreatmentDataError, match="destructive"):
        load_treatment_manifest(repeated)


@pytest.mark.parametrize(
    ("column", "value", "message"),
    [
        ("concentration_ug_per_ml", "-1", "non-negative"),
        ("exposure_hours", "-1", "non-negative"),
        ("micrometers_per_pixel", "0", "positive"),
        ("viability_fraction", "-0.1", "non-negative"),
    ],
)
def test_invalid_treatment_measurements_are_rejected(
    tmp_path: Path, column: str, value: str, message: str
) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    rows[0][column] = value
    _write_rows(manifest, rows)
    with pytest.raises(TreatmentDataError, match=message):
        load_treatment_manifest(manifest)


def _write_rows(path: Path, rows: list[dict[str, str]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def test_image_paths_cannot_escape_the_manifest_directory(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    rows[0]["image_path"] = "../../../etc/passwd"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    with pytest.raises(TreatmentDataError, match="escapes the manifest directory"):
        load_treatment_manifest(manifest)


def test_benjamini_hochberg_matches_a_worked_example() -> None:
    q = benjamini_hochberg([0.01, 0.02, 0.03, 0.04, 0.05])
    assert q == pytest.approx([0.05, 0.05, 0.05, 0.05, 0.05])
    assert benjamini_hochberg([]) == []
    # Correction can only make a p-value larger.
    raw = [0.001, 0.5, 0.9]
    assert all(a >= b for a, b in zip(benjamini_hochberg(raw), raw, strict=True))


def test_benjamini_hochberg_enforces_monotonicity() -> None:
    """Without the running minimum, a later q-value can drop below an earlier one.

    For p = [0.01, 0.04, 0.03] the rank-scaled values in sorted order are
    [0.03, 0.045, 0.04]. Without the step-up minimum the middle one stays at
    0.045, so the *smaller* p-value 0.03 would receive a larger q-value than the
    larger p-value 0.04 — an ordering violation that makes the correction
    incoherent. The correct answer pulls it down to 0.04.
    """
    assert benjamini_hochberg([0.01, 0.04, 0.03]) == pytest.approx([0.03, 0.04, 0.04])
    q = benjamini_hochberg([0.001, 0.9, 0.02, 0.5, 0.03])
    ordered = [q[index] for index in np.argsort([0.001, 0.9, 0.02, 0.5, 0.03])]
    assert all(a <= b + 1e-12 for a, b in zip(ordered, ordered[1:], strict=False))


def test_benjamini_hochberg_survives_a_non_finite_p_value() -> None:
    """One undefined test used to turn every q-value in the family into NaN."""
    q = benjamini_hochberg([0.001, float("nan"), 0.5])
    assert math.isnan(q[1])
    assert q[0] == pytest.approx(0.002) and q[2] == pytest.approx(0.5)


def test_dose_response_fit_recovers_a_known_ic50() -> None:
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 3, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    fit = fit_dose_response(concentrations, responses)
    assert fit["fitted"]
    assert fit["ic50_ug_per_ml"] == pytest.approx(30.0, rel=0.2)
    assert fit["r_squared"] > 0.99


@pytest.mark.parametrize(
    "concentrations",
    [
        # One concentration: nothing to fit.
        [0.0, 10.0, 10.0],
        # Four points, four parameters: zero residual degrees of freedom.
        [0.0, 1.0, 10.0, 100.0, 1000.0],
        # Five distinct concentrations but only 6 non-zero wells.
        [0.0, 1.0, 1.0, 3.0, 10.0, 30.0, 100.0],
    ],
)
def test_dose_response_refuses_a_design_that_cannot_constrain_four_parameters(
    concentrations: list[float],
) -> None:
    values = np.linspace(1.0, 0.2, len(concentrations))
    fit = fit_dose_response(np.array(concentrations), values)
    assert not fit["fitted"]
    assert "at least 5 distinct non-zero concentrations" in fit["reason"]


def test_dose_response_fits_once_the_design_is_adequate() -> None:
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 2, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    assert fit_dose_response(concentrations, responses)["fitted"]


def test_a_bootstrap_interval_is_withheld_when_resamples_do_not_converge() -> None:
    """A CI from only the well-behaved resamples is biased narrow, so report none."""
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 3, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    fit = fit_dose_response(concentrations, responses)
    assert 0.0 <= fit["bootstrap_convergence_rate"] <= 1.0
    if fit["bootstrap_convergence_rate"] < 0.8:
        assert fit["ic50_ci95"] is None
        assert "biased narrow" in fit["ic50_ci95_note"]
    else:
        assert fit["ic50_ci95"] is not None


def test_an_extrapolated_ic50_is_flagged() -> None:
    concentrations = np.array([1, 2, 3, 4, 5, 6] * 3, dtype=float)
    responses = np.linspace(1.0, 0.95, concentrations.size)
    fit = fit_dose_response(concentrations, responses)
    if fit["fitted"] and not fit["ic50_within_tested_range"]:
        assert "extrapolation" in fit["warning"]


def test_leave_one_day_out_needs_more_than_one_day() -> None:
    result = leave_one_day_out(np.zeros((4, 2)), np.zeros(4), ["d1"] * 4)
    assert not result["evaluated"]


def test_leave_one_day_out_finds_real_signal_and_rejects_noise() -> None:
    rng = np.random.default_rng(1)
    days = ["d1"] * 12 + ["d2"] * 12
    features = rng.normal(size=(24, 2))
    signal = 2.0 * features[:, 0] + rng.normal(0, 0.1, size=24)
    strong = leave_one_day_out(features, signal, days, permutations=200, seed=2)
    assert strong["r_squared"] > 0.8
    assert strong["permutation_p_value"] < 0.05

    noise = rng.normal(size=24)
    weak = leave_one_day_out(features, noise, days, permutations=200, seed=2)
    assert weak["permutation_p_value"] > 0.05


def test_end_to_end_analysis_detects_a_planted_dose_response(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "study", effect=True, seed=3)
    report = run_treatment_analysis(
        manifest, tmp_path / "out", instance_method="connected_components", min_area=5
    )

    assert report["segmenter"] == "classical-baseline"
    assert report["wells"] == 20
    assert report["experiment_days"] == ["2026-03-01", "2026-03-08"]
    area = report["dose_response"]["area_pixels_mean"]
    # Cells were made to shrink with dose.
    assert area["spearman_rho"] < -0.7
    assert area["q_value_bh"] < 0.05
    assert area["significant_at_q_0.05"]

    prediction = report["viability_linkage"]["prediction"]
    assert prediction["evaluated"]
    assert prediction["r_squared"] > 0.5
    assert prediction["permutation_p_value"] < 0.05

    assert (tmp_path / "out" / "treatment_report.json").is_file()
    assert (tmp_path / "out" / "well_level_summary.csv").is_file()
    assert (tmp_path / "out" / "treatment_morphology.csv").is_file()
    persisted = json.loads((tmp_path / "out" / "treatment_report.json").read_text())
    assert "does not establish a mechanism" in persisted["claim_boundary"]


def test_end_to_end_analysis_does_not_invent_a_dose_response(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "null", effect=False, seed=11)
    report = run_treatment_analysis(
        manifest, tmp_path / "out", instance_method="connected_components", min_area=5
    )
    area = report["dose_response"]["area_pixels_mean"]
    assert area["q_value_bh"] > 0.05
    assert not area["significant_at_q_0.05"]


def test_a_missing_image_is_reported_rather_than_silently_skipped(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "gap")
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    (tmp_path / "gap" / rows[0]["image_path"]).unlink()
    with pytest.raises(TreatmentDataError, match="is missing"):
        run_treatment_analysis(manifest, tmp_path / "out")


def test_the_well_is_the_unit_so_extra_fields_do_not_inflate_n(tmp_path: Path) -> None:
    few = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "a", fields=2, seed=5),
        tmp_path / "outa",
        instance_method="connected_components",
        min_area=5,
    )
    many = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "b", fields=6, seed=5),
        tmp_path / "outb",
        instance_method="connected_components",
        min_area=5,
    )
    assert few["wells"] == many["wells"]
    assert many["images_analysed"] == 3 * few["images_analysed"]


# --------------------------------------------------- design checks added later


def test_a_single_experiment_day_is_refused(tmp_path: Path) -> None:
    """Nothing can be validated on a day the model did not see."""
    manifest = build_synthetic_experiment(tmp_path, days=("2026-03-01",))
    with pytest.raises(TreatmentDataError, match="only one experiment day"):
        load_treatment_manifest(manifest)


def test_a_zero_dose_well_is_not_automatically_a_vehicle_control(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        if row["control_type"] == "vehicle":
            row["control_type"] = "untreated"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    with pytest.raises(TreatmentDataError, match="control_type='vehicle'"):
        load_treatment_manifest(manifest)


def test_controls_and_replicates_are_validated_inside_each_arm(tmp_path: Path) -> None:
    manifest = _with_second_treatment(build_synthetic_experiment(tmp_path), "second extract")
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    rows = [
        row
        for row in rows
        if not (row["treatment"] == "second extract" and float(row["concentration_ug_per_ml"]) == 0)
    ]
    _write_rows(manifest, rows)
    with pytest.raises(TreatmentDataError, match="second extract.*no zero-concentration"):
        load_treatment_manifest(manifest)


def test_every_plate_and_time_requires_its_own_vehicle(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        if row["experiment_day"] == "2026-03-08" and row["control_type"] == "vehicle":
            row["control_type"] = "untreated"
    _write_rows(manifest, rows)
    with pytest.raises(TreatmentDataError, match="no matched control_type='vehicle'"):
        load_treatment_manifest(manifest)


def test_one_physical_well_cannot_change_treatment_metadata(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    rows[0]["treatment"] = "different treatment"
    _write_rows(manifest, rows)
    with pytest.raises(TreatmentDataError, match="physical well is assigned conflicting"):
        load_treatment_manifest(manifest)


# ------------------------------------------------ leave-one-day-out correctness


def test_a_day_that_cannot_be_trained_against_is_not_scored_as_zero() -> None:
    """Skipped folds used to keep a prediction of 0.0 and enter R^2 as real."""
    features = np.random.default_rng(0).normal(size=(6, 2))
    targets = np.arange(6.0)
    result = leave_one_day_out(features, targets, ["a"] + ["b"] * 5, permutations=20)
    assert result["evaluated"] is False
    assert result["wells_skipped"] == 5
    assert "at least two wells on the other days" in result["reason"]


def test_within_day_r_squared_is_reported_next_to_the_plain_one() -> None:
    rng = np.random.default_rng(5)
    days = ["d1"] * 10 + ["d2"] * 10
    features = rng.normal(size=(20, 2))
    targets = 1.5 * features[:, 0] + rng.normal(0, 0.1, size=20)
    result = leave_one_day_out(features, targets, days, permutations=100, seed=1)
    assert result["evaluated"]
    assert "within_day_r_squared" in result
    assert result["wells_scored"] == 20 and result["wells_skipped"] == 0
    assert 0.0 <= result["r_squared_percentile_in_null"] <= 1.0
    assert "within_day_r_squared" in result["interpretation"]


def test_a_pure_between_day_difference_inflates_plain_r2_but_not_within_day_r2() -> None:
    """The whole point of reporting both numbers.

    Three days with evenly spaced batch offsets, and a feature that carries only
    the offset. Trained on two days, the model extrapolates the third day's level
    correctly, so R^2 against the global mean looks excellent — while explaining
    nothing at all about which well within a day has higher viability.
    """
    rng = np.random.default_rng(11)
    days = ["d1"] * 8 + ["d2"] * 8 + ["d3"] * 8
    offsets = np.array([0.0] * 8 + [5.0] * 8 + [10.0] * 8)
    features = np.column_stack([offsets + rng.normal(0, 0.02, 24), rng.normal(size=24)])
    targets = offsets + rng.normal(0, 0.3, 24)
    result = leave_one_day_out(features, targets, days, permutations=50, seed=3)
    assert result["evaluated"]
    # Between-day structure alone explains nearly all variance around the global mean...
    assert result["r_squared"] > 0.9
    # ...and essentially none of the variance within a day.
    assert result["within_day_r_squared"] < 0.5
    assert result["within_day_r_squared"] < result["r_squared"]


# ------------------------------------------------- day-stratified dose response


def test_a_pure_day_effect_is_not_reported_as_a_dose_effect() -> None:
    """Concentration confounded with day: the pooled test is fooled, the blocked one is not."""
    days = np.array(["d1"] * 8 + ["d2"] * 8)
    # Day 1 received only low doses, day 2 only high doses.
    concentrations = np.array([0, 0, 10, 10, 20, 20, 30, 30] * 2, dtype=float)
    concentrations[8:] += 100
    values = np.where(days == "d1", 1.0, 3.0) + np.random.default_rng(0).normal(0, 0.01, 16)
    result = stratified_spearman(concentrations, values, days, permutations=500, seed=1)
    assert result["p_value"] < 0.01  # pooled: looks like a strong dose response
    assert result["p_value_day_stratified"] > 0.05  # blocked: it was the day


def test_a_real_within_day_dose_effect_survives_blocking() -> None:
    days = np.array(["d1"] * 10 + ["d2"] * 10)
    concentrations = np.array([0, 10, 20, 30, 40] * 4, dtype=float)
    values = -0.05 * concentrations + np.where(days == "d1", 0.0, 2.0)
    result = stratified_spearman(concentrations, values, days, permutations=500, seed=1)
    assert result["spearman_rho"] < -0.5
    assert result["p_value_day_stratified"] < 0.05


# -------------------------------------------------- confirmatory vs exploratory


def test_features_are_labelled_by_what_they_actually_measure(tmp_path: Path) -> None:
    report = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "s", seed=3),
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=200,
    )
    kinds = report["feature_kinds"]
    assert kinds["total_area_pixels"] == "density"
    assert kinds["area_pixels_mean"] == "density-contaminated"
    assert kinds["circularity_mean"] == "shape"
    assert "fewer cells at higher dose" in report["confluency_caveat"]
    for name, entry in report["dose_response"].items():
        assert entry["feature_kind"] == kinds.get(name, entry["feature_kind"])


def test_the_confirmatory_endpoint_is_tested_separately_from_the_exploratory_model(
    tmp_path: Path,
) -> None:
    report = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "s", seed=3),
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=200,
    )
    linkage = report["viability_linkage"]
    assert "confirmatory_prediction" in linkage
    assert "exploratory_prediction" in linkage
    confirmatory = linkage["confirmatory_prediction"]
    assert confirmatory["feature"] == report["primary_feature"]
    # The pre-specified endpoint must be a shape feature, not a confluency proxy.
    assert report["feature_kinds"].get(report["primary_feature"]) == "shape"


def test_within_day_centring_is_on_by_default_and_narrows_the_claim() -> None:
    rng = np.random.default_rng(9)
    days = ["d1"] * 10 + ["d2"] * 10
    features = rng.normal(size=(20, 1))
    targets = 0.8 * features[:, 0] + rng.normal(0, 0.2, 20)
    result = leave_one_day_out(features, targets, days, permutations=100, seed=1)
    assert result["centred_by_day"] is True
    assert "relative to its own experiment day" in result["claim"]

    uncentred = leave_one_day_out(
        features, targets, days, permutations=100, seed=1, centre_by_day=False
    )
    assert uncentred["centred_by_day"] is False
    assert "confound" in uncentred["claim"]


def _null_confounded_experiment(seed: int, correlation: float) -> tuple:
    """Three days; morphology and viability each carry an unrelated day-level shift."""
    rng = np.random.default_rng(seed)
    days: list[str] = []
    feature: list[np.ndarray] = []
    viability: list[np.ndarray] = []
    for index in range(3):
        morphology_shift = rng.normal(0, 1.0)
        viability_shift = rng.normal(0, 0.3)
        latent = rng.normal(size=10)
        noise = rng.normal(size=10)
        days += [f"d{index}"] * 10
        feature.append(latent + morphology_shift)
        viability.append(
            0.2 * (correlation * latent + np.sqrt(1 - correlation**2) * noise)
            + viability_shift
            + 0.6
        )
    return np.concatenate(feature)[:, None], np.concatenate(viability), days


def test_centring_detects_effects_that_confounded_day_shifts_would_otherwise_hide() -> None:
    """The measured reason centring is the default.

    A model fitted across days learns a slope corrupted by day-level shifts that
    are independent in morphology and in viability. Fitted to within-day
    deviations it does not. Counted over several independent experiments at a
    moderate effect size, centring detects strictly more of them.
    """
    centred_hits = 0
    uncentred_hits = 0
    for trial in range(6):
        features, targets, days = _null_confounded_experiment(trial, correlation=0.5)
        centred = leave_one_day_out(features, targets, days, permutations=150, seed=trial)
        uncentred = leave_one_day_out(
            features, targets, days, permutations=150, seed=trial, centre_by_day=False
        )
        centred_hits += centred["permutation_p_value"] < 0.05
        uncentred_hits += uncentred["permutation_p_value"] < 0.05
    assert centred_hits > uncentred_hits


def test_centring_does_not_inflate_the_false_positive_rate() -> None:
    """Power is worthless if it comes from a broken null. Ten independent nulls."""
    significant = 0
    for trial in range(10):
        rng = np.random.default_rng(100 + trial)
        days: list[str] = []
        feature: list[np.ndarray] = []
        viability: list[np.ndarray] = []
        for index in range(3):
            days += [f"d{index}"] * 10
            feature.append(rng.normal(size=10) + rng.normal(0, 1.0))
            viability.append(rng.normal(0, 0.2, 10) + rng.normal(0, 0.3) + 0.6)
        result = leave_one_day_out(
            np.concatenate(feature)[:, None],
            np.concatenate(viability),
            days,
            permutations=200,
            seed=trial,
        )
        significant += result["permutation_p_value"] < 0.05
    # At alpha = 0.05 over 10 pure nulls, more than two hits would be alarming.
    assert significant <= 2


# ------------------------------------------------------------------- kinetics


def test_kinetics_recovers_a_planted_half_time() -> None:
    hours = np.array([0, 3, 6, 12, 24, 48], dtype=float)
    values = exponential_approach(hours, 1.0, 0.2, math.log(2) / 9.0)
    fit = fit_kinetics(hours, values)
    assert fit["fitted"]
    assert fit["half_time_hours"] == pytest.approx(9.0, rel=0.05)
    assert fit["saturating_r_squared"] > 0.99


@pytest.mark.parametrize("hours", [[0.0, 24.0], [24.0, 24.0, 24.0], [0.0, 0.0, 12.0]])
def test_kinetics_refuses_fewer_than_three_distinct_times(hours: list[float]) -> None:
    fit = fit_kinetics(np.array(hours), np.linspace(1.0, 0.5, len(hours)))
    assert not fit["fitted"]
    assert "three distinct exposure times" in fit["reason"]


def test_kinetics_quotes_no_half_time_when_the_response_has_not_plateaued() -> None:
    """A half-time far beyond the observation window is extrapolation, not a result."""
    hours = np.array([0, 6, 12, 18, 24], dtype=float)
    values = 1.0 - 0.001 * hours  # barely moving; the plateau is nowhere in sight
    fit = fit_kinetics(hours, values)
    assert fit["fitted"]
    assert fit["half_time_hours"] is None
    assert "not visibly plateaued" in fit["model_note"] or "linear" in fit["model_note"].lower()


def test_a_single_timepoint_study_reports_no_kinetics_rather_than_guessing(
    tmp_path: Path,
) -> None:
    report = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "flat", seed=3),
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=100,
    )
    kinetics = report["kinetics"]
    assert kinetics["evaluated"] is False
    assert "three distinct exposure times" in kinetics["reason"]


def test_a_time_course_study_measures_how_quickly_changes_occur(tmp_path: Path) -> None:
    """The stated goal that had no implementation at all."""
    manifest = build_synthetic_experiment(
        tmp_path / "course",
        timepoints=(0.0, 6.0, 12.0, 24.0, 48.0),
        half_time_hours=12.0,
        longitudinal=True,
        fields=1,
        seed=5,
    )
    report = run_treatment_analysis(
        manifest,
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=100,
    )
    kinetics = report["kinetics"]
    assert kinetics["evaluated"] is True
    assert kinetics["design"] == "longitudinal"
    assert kinetics["exposure_hours"] == [0.0, 6.0, 12.0, 24.0, 48.0]
    assert kinetics["units_with_a_rate"] > 0
    assert "individual cells" in kinetics["caveat"]


def test_a_destructive_design_is_reported_as_cross_sectional(tmp_path: Path) -> None:
    """Rates fitted across wells are confounded, and the report must say so."""
    manifest = build_synthetic_experiment(
        tmp_path / "destructive",
        timepoints=(0.0, 12.0, 24.0, 48.0),
        longitudinal=False,
        wells_per_condition=2,
        fields=1,
        seed=6,
    )
    report = run_treatment_analysis(
        manifest,
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=100,
    )
    kinetics = report["kinetics"]
    assert kinetics["design"] == "cross-sectional"
    assert "confounded with well-to-well variation" in kinetics["design_note"]


def test_the_rate_of_change_itself_is_tested_against_dose(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(
        tmp_path / "course",
        timepoints=(0.0, 6.0, 12.0, 24.0, 48.0),
        longitudinal=True,
        fields=1,
        seed=7,
    )
    report = run_treatment_analysis(
        manifest,
        tmp_path / "out",
        instance_method="connected_components",
        min_area=5,
        permutations=100,
    )
    dose = report["kinetics"]["dose_dependence_of_rate"]
    assert dose["evaluated"] is True
    assert "rate of change itself" in dose["question"]
    assert dose["spearman_rho"] is not None


# ------------------------------------------------------------ planning a study


def test_the_planner_emits_a_design_that_satisfies_every_enforced_requirement(
    tmp_path: Path,
) -> None:
    summary = plan_experiment(tmp_path / "plan.csv")
    assert all(summary["requirements_met"].values()), summary["requirements_met"]
    assert summary["rows_to_fill"] == summary["images_to_capture"]
    with (tmp_path / "plan.csv").open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    assert len(rows) == summary["rows_to_fill"]
    # Image paths are blank on purpose: this is a collection checklist.
    assert all(row["image_path"] == "" for row in rows)
    assert all(row["viability_fraction"] == "" for row in rows)
    # Every column the analysis requires is present.
    for column in REQUIRED_COLUMNS:
        assert column in rows[0]


def test_a_planned_design_passes_the_design_check_once_filled_in(tmp_path: Path) -> None:
    """The planner and the validator must agree, or the plan is worthless."""
    path = tmp_path / "plan.csv"
    plan_experiment(path, fields=1, wells_per_condition=2)
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    images = tmp_path / "images"
    images.mkdir()
    filled = []
    for index, row in enumerate(rows):
        # Positive controls are kept. They used to be deleted here because the
        # planner wrote them with no concentration and the loader then refused
        # them, so the only test covering the planner quietly worked around the
        # bug it should have caught.
        name = f"img{index}.png"
        Image.fromarray(np.full((32, 32), 128, dtype=np.uint8)).save(images / name)
        filled.append({**row, "image_path": f"images/{name}", "viability_fraction": "0.5"})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(filled[0]))
        writer.writeheader()
        writer.writerows(filled)
    records = load_treatment_manifest(path)
    assert len(records) == len(filled)


def test_an_inadequate_plan_is_reported_as_inadequate(tmp_path: Path) -> None:
    summary = plan_experiment(
        tmp_path / "thin.csv",
        days=("only-day",),
        concentrations=(0.0, 100.0),
        exposure_hours=(24.0,),
        wells_per_condition=1,
    )
    met = summary["requirements_met"]
    assert met["vehicle_control"] is True
    assert met["two_or_more_days"] is False
    assert met["two_or_more_wells_per_condition"] is False
    assert met["ic50_identifiable"] is False
    assert met["half_time_identifiable"] is False


class TestStratification:
    """A dose response only means something inside one cell line, treatment and time.

    Before this, every well row went into one correlation regardless of what was
    in the well, and a well imaged at three timepoints contributed three
    correlated rows that the permutation treated as exchangeable. Both are ways
    of manufacturing a p-value, and neither had been caught because no real
    treatment images have ever been analysed.
    """

    def test_a_single_condition_still_gets_a_pooled_answer(self, tmp_path: Path) -> None:
        """One stratum is not pooling, and must keep working exactly as before."""
        manifest = build_synthetic_experiment(tmp_path, timepoints=(24.0,))
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=60)
        assert len(report["analysis_strata"]) == 1
        assert "pooled" not in report["dose_response"]
        assert report["dose_response"]["area_pixels_mean"]["wells"] > 0

    def test_two_exposure_times_are_not_pooled(self, tmp_path: Path) -> None:
        """Pooling exposure times confounds how much with how long."""
        manifest = build_synthetic_experiment(tmp_path, timepoints=(6.0, 24.0))
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=60)
        assert len(report["analysis_strata"]) == 2
        assert report["dose_response"]["pooled"] is False
        assert "confounds" in report["dose_response"]["reason"]

    def test_each_stratum_is_still_analysed(self, tmp_path: Path) -> None:
        """Refusing to pool must not mean refusing to answer."""
        manifest = build_synthetic_experiment(tmp_path, timepoints=(6.0, 24.0))
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=60)
        for label, entry in report["per_stratum"].items():
            assert entry["dose_response"], label
            assert entry["usable"], label

    def test_two_treatments_are_not_pooled(self, tmp_path: Path) -> None:
        """A microlitre of extract and a micromolar of doxorubicin are not one axis."""
        manifest = _with_second_treatment(build_synthetic_experiment(tmp_path), "doxorubicin")
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=60)
        assert len(report["analysis_strata"]) == 2
        assert report["dose_response"]["pooled"] is False

    def test_viability_and_kinetics_are_not_pooled(self, tmp_path: Path) -> None:
        manifest = _with_second_treatment(
            build_synthetic_experiment(tmp_path, timepoints=(0.0, 12.0, 24.0), longitudinal=True),
            "second extract",
        )
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=30)
        assert report["viability_linkage"]["pooled"] is False
        assert len(report["viability_linkage"]["per_stratum"]) == 6
        assert report["kinetics"]["pooled"] is False
        assert len(report["kinetics"]["per_stratum"]) == 2

    def test_q_values_cover_all_strata(self, tmp_path: Path) -> None:
        manifest = _with_second_treatment(build_synthetic_experiment(tmp_path), "second extract")
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=30)
        tests = [
            entry
            for stratum in report["per_stratum"].values()
            for entry in stratum["dose_response"].values()
            if isinstance(entry, dict) and "p_value_day_stratified" in entry
        ]
        assert tests
        assert all("q_value_bh_global" in entry for entry in tests)
        assert all(entry["q_value_bh"] >= entry["q_value_bh_within_stratum"] for entry in tests)

    def test_a_well_appears_once_within_a_stratum(self, tmp_path: Path) -> None:
        """The property that makes permuting wells legitimate at all."""
        manifest = build_synthetic_experiment(tmp_path, timepoints=(6.0, 24.0), longitudinal=True)
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=30)
        for label, entry in report["per_stratum"].items():
            wells = {
                d["wells"]
                for d in entry["dose_response"].values()
                if isinstance(d.get("wells"), int)
            }
            assert len(wells) <= 1, f"{label} disagrees on its own well count"

    def test_the_stratum_fields_are_reported(self, tmp_path: Path) -> None:
        """A reader cannot judge a stratified result without knowing the strata."""
        manifest = build_synthetic_experiment(tmp_path)
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=30)
        assert report["stratum_fields"] == ["cell_line", "treatment", "exposure_hours"]

    def test_cell_line_reaches_the_well_rows(self, tmp_path: Path) -> None:
        """It was dropped entirely, so two cell lines could silently merge."""
        manifest = build_synthetic_experiment(tmp_path)
        report = run_treatment_analysis(manifest, tmp_path / "out", permutations=30)
        assert any("cell_line=" in label for label in report["analysis_strata"])


def _with_second_treatment(manifest: Path, name: str) -> Path:
    """Clone a complete valid dose series under a second treatment name."""
    with manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    clones: list[dict[str, str]] = []
    for index, row in enumerate(rows):
        clone = dict(row)
        source = manifest.parent / row["image_path"]
        target = source.with_name(f"second_{index}_{source.name}")
        shutil.copy(source, target)
        clone["image_path"] = str(target.relative_to(manifest.parent))
        clone["well_id"] = f"second-{row['well_id']}"
        clone["treatment"] = name
        clones.append(clone)
    rows.extend(clones)
    out = manifest.with_name("two_treatments.csv")
    with out.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return out


class TestPositiveControls:
    """A positive control is a drug at a dose, and must survive the round trip.

    The planner wrote these rows with a NaN concentration, which the manifest
    loader then refused. The two halves of the pipeline disagreed, and the only
    test covering it deleted the rows before loading them -- so the workflow the
    planner describes had never once been run end to end.
    """

    def test_the_planner_gives_positive_controls_a_real_concentration(self, tmp_path: Path) -> None:
        path = tmp_path / "plan.csv"
        plan_experiment(path, fields=1, wells_per_condition=2)
        with path.open(newline="", encoding="utf-8") as handle:
            rows = [row for row in csv.DictReader(handle) if row["control_type"] == "positive"]
        assert rows, "the default plan should include a positive control"
        for row in rows:
            assert float(row["concentration_ug_per_ml"]) > 0
            assert row["treatment"] == "doxorubicin"

    def test_the_control_is_its_own_treatment_not_the_extract(self, tmp_path: Path) -> None:
        """Otherwise it lands in the extract's dose series and distorts it."""
        path = tmp_path / "plan.csv"
        plan_experiment(path, fields=1, wells_per_condition=2)
        with path.open(newline="", encoding="utf-8") as handle:
            treatments = {row["treatment"] for row in csv.DictReader(handle)}
        assert len(treatments) == 2

    def test_a_reference_arm_is_not_reported_as_a_failed_dose_response(self) -> None:
        """One concentration is not a dose series, and saying 'no response' would mislead."""
        wells = [
            {
                "experiment_day": "day-1",
                "concentration_ug_per_ml": 5.0,
                "area_pixels_mean": 100.0 + index,
            }
            for index in range(4)
        ]
        result = _dose_response_for(wells, ["area_pixels_mean"], permutations=10)
        assert result["dose_response"]["dose_series"] is False
        assert "reference arm" in result["dose_response"]["reason"]
        assert result["dose_response"]["feature_means"]["area_pixels_mean"] > 0

    def test_a_real_dose_series_is_still_analysed(self) -> None:
        wells = [
            {
                "experiment_day": "day-1",
                "concentration_ug_per_ml": float(dose),
                "area_pixels_mean": 100.0 - dose,
            }
            for dose in (0, 25, 50, 100)
        ]
        result = _dose_response_for(wells, ["area_pixels_mean"], permutations=10)
        assert "dose_series" not in result["dose_response"]
        assert result["usable"] == ["area_pixels_mean"]
