"""The Tribonema phase: manifest validation, design checks, and statistics.

Every dataset here is synthetic and generated by the test suite. It exists to
prove the analysis behaves correctly — that it finds a planted dose response and,
just as importantly, that it does not invent one when there is none.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np
import pytest
from conftest import build_synthetic_experiment

from tribovision.treatment import (
    TreatmentDataError,
    benjamini_hochberg,
    fit_dose_response,
    four_parameter_logistic,
    leave_one_day_out,
    load_treatment_manifest,
    run_treatment_analysis,
    write_template,
)


def test_template_lists_every_required_column(tmp_path: Path) -> None:
    path = write_template(tmp_path / "template.csv")
    with path.open() as handle:
        header = next(csv.reader(handle))
    for column in (
        "experiment_day",
        "plate_id",
        "well_id",
        "concentration_ug_per_ml",
        "exposure_hours",
        "control_type",
        "replicate",
    ):
        assert column in header


def test_a_manifest_missing_required_columns_is_rejected(tmp_path: Path) -> None:
    path = tmp_path / "bad.csv"
    path.write_text("image_path,treatment\nx.png,extract\n", encoding="utf-8")
    with pytest.raises(TreatmentDataError, match="missing required column"):
        load_treatment_manifest(path)


def test_a_design_without_controls_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, concentrations=(25.0, 50.0, 100.0))
    with pytest.raises(TreatmentDataError, match="no zero-concentration control"):
        load_treatment_manifest(manifest)


def test_a_design_with_one_concentration_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, concentrations=(0.0,))
    with pytest.raises(TreatmentDataError, match="only one concentration"):
        load_treatment_manifest(manifest)


def test_a_design_without_replicate_wells_is_refused(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, days=("2026-03-01",), wells_per_condition=1)
    with pytest.raises(TreatmentDataError, match="fewer than two independent wells"):
        load_treatment_manifest(manifest)


def test_a_sound_design_loads(tmp_path: Path) -> None:
    records = load_treatment_manifest(build_synthetic_experiment(tmp_path))
    assert len(records) == 2 * 5 * 2 * 2
    assert {record.experiment_day for record in records} == {"2026-03-01", "2026-03-08"}


def test_viability_is_derived_from_absorbance_when_not_given(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path, days=("d1", "d2"))
    rows = list(csv.DictReader(manifest.open()))
    for row in rows:
        row["viability_fraction"] = ""
        row["mts_absorbance"] = "0.8"
        row["mts_blank_absorbance"] = "0.1"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    records = load_treatment_manifest(manifest)
    assert records[0].viability_fraction == pytest.approx(0.7)


def test_image_paths_cannot_escape_the_manifest_directory(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path)
    rows = list(csv.DictReader(manifest.open()))
    rows[0]["image_path"] = "../../../etc/passwd"
    with manifest.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    with pytest.raises(TreatmentDataError, match="escapes the manifest directory"):
        load_treatment_manifest(manifest)


def test_benjamini_hochberg_matches_a_worked_example() -> None:
    q = benjamini_hochberg([0.01, 0.02, 0.03, 0.04, 0.05])
    assert q == pytest.approx([0.05, 0.05, 0.05, 0.05, 0.05])
    assert benjamini_hochberg([]) == []
    # Correction can only make a p-value larger.
    raw = [0.001, 0.5, 0.9]
    assert all(a >= b for a, b in zip(benjamini_hochberg(raw), raw, strict=True))


def test_dose_response_fit_recovers_a_known_ic50() -> None:
    concentrations = np.array([0, 1, 3, 10, 30, 100, 300, 1000] * 3, dtype=float)
    responses = four_parameter_logistic(
        np.log10(np.maximum(concentrations, 1e-9)), 0.0, 1.0, 30.0, -1.0
    )
    fit = fit_dose_response(concentrations, responses)
    assert fit["fitted"]
    assert fit["ic50_ug_per_ml"] == pytest.approx(30.0, rel=0.2)
    assert fit["r_squared"] > 0.99


def test_dose_response_refuses_to_fit_too_few_concentrations() -> None:
    fit = fit_dose_response(np.array([0.0, 10.0, 10.0]), np.array([1.0, 0.5, 0.5]))
    assert not fit["fitted"]
    assert "at least three distinct" in fit["reason"]


def test_an_extrapolated_ic50_is_flagged() -> None:
    concentrations = np.array([1, 2, 3, 4, 5, 6] * 3, dtype=float)
    responses = np.linspace(1.0, 0.95, concentrations.size)
    fit = fit_dose_response(concentrations, responses)
    if fit["fitted"] and not fit["ic50_within_tested_range"]:
        assert "extrapolation" in fit["warning"]


def test_leave_one_day_out_needs_more_than_one_day() -> None:
    result = leave_one_day_out(np.zeros((4, 2)), np.zeros(4), ["d1"] * 4)
    assert not result["evaluated"]


def test_leave_one_day_out_finds_real_signal_and_rejects_noise() -> None:
    rng = np.random.default_rng(1)
    days = ["d1"] * 12 + ["d2"] * 12
    features = rng.normal(size=(24, 2))
    signal = 2.0 * features[:, 0] + rng.normal(0, 0.1, size=24)
    strong = leave_one_day_out(features, signal, days, permutations=200, seed=2)
    assert strong["r_squared"] > 0.8
    assert strong["permutation_p_value"] < 0.05

    noise = rng.normal(size=24)
    weak = leave_one_day_out(features, noise, days, permutations=200, seed=2)
    assert weak["permutation_p_value"] > 0.05


def test_end_to_end_analysis_detects_a_planted_dose_response(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "study", effect=True, seed=3)
    report = run_treatment_analysis(
        manifest, tmp_path / "out", instance_method="connected_components", min_area=5
    )

    assert report["segmenter"] == "classical-baseline"
    assert report["wells"] == 20
    assert report["experiment_days"] == ["2026-03-01", "2026-03-08"]
    area = report["dose_response"]["area_pixels_mean"]
    # Cells were made to shrink with dose.
    assert area["spearman_rho"] < -0.7
    assert area["q_value_bh"] < 0.05
    assert area["significant_at_q_0.05"]

    prediction = report["viability_linkage"]["prediction"]
    assert prediction["evaluated"]
    assert prediction["r_squared"] > 0.5
    assert prediction["permutation_p_value"] < 0.05

    assert (tmp_path / "out" / "treatment_report.json").is_file()
    assert (tmp_path / "out" / "well_level_summary.csv").is_file()
    assert (tmp_path / "out" / "treatment_morphology.csv").is_file()
    persisted = json.loads((tmp_path / "out" / "treatment_report.json").read_text())
    assert "does not establish a mechanism" in persisted["claim_boundary"]


def test_end_to_end_analysis_does_not_invent_a_dose_response(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "null", effect=False, seed=11)
    report = run_treatment_analysis(
        manifest, tmp_path / "out", instance_method="connected_components", min_area=5
    )
    area = report["dose_response"]["area_pixels_mean"]
    assert area["q_value_bh"] > 0.05
    assert not area["significant_at_q_0.05"]


def test_a_missing_image_is_reported_rather_than_silently_skipped(tmp_path: Path) -> None:
    manifest = build_synthetic_experiment(tmp_path / "gap")
    rows = list(csv.DictReader(manifest.open()))
    (tmp_path / "gap" / rows[0]["image_path"]).unlink()
    with pytest.raises(TreatmentDataError, match="is missing"):
        run_treatment_analysis(manifest, tmp_path / "out")


def test_the_well_is_the_unit_so_extra_fields_do_not_inflate_n(tmp_path: Path) -> None:
    few = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "a", fields=2, seed=5),
        tmp_path / "outa",
        instance_method="connected_components",
        min_area=5,
    )
    many = run_treatment_analysis(
        build_synthetic_experiment(tmp_path / "b", fields=6, seed=5),
        tmp_path / "outb",
        instance_method="connected_components",
        min_area=5,
    )
    assert few["wells"] == many["wells"]
    assert many["images_analysed"] == 3 * few["images_analysed"]
