"""Generate the values the browser must reproduce, from the Python package.

    python scripts/generate_parity_fixtures.py            # write the fixtures
    python scripts/generate_parity_fixtures.py --check    # confirm they still match

The website reimplements TriboGuard's arithmetic so it can run without a server.
A reimplementation that drifts is worse than no demo, because both halves keep
working and quietly disagree, so these fixtures pin the two together.

Values are written at full double precision. An earlier version rounded them to
ten decimal places, which put a floor of about 1e-10 on the agreement any test
could assert -- the fixtures, not the code, were the least accurate thing in the
comparison.

``--check`` compares numbers within a relative 1e-12 rather than diffing text,
for the reason given in ``generate_chi2_table.py``: machines disagree in the
last digit, and a text diff reports that noise as drift.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from triboguard import design

OUT = Path("web/lib/__fixtures__/python-parity.json")
WELL_COUNTS = (1, 2, 3, 4, 6, 8, 12, 24, 48, 96, 200)
CONFIDENCES = (0.95, 0.90)
RATIO_TARGETS = (2.0, 3.0, 5.0, 10.0)
DESIGNS = ((3, 4), (3, 2), (12, 5), (24, 3))
RELATIVE_TOLERANCE = 1e-12


def fixtures() -> dict[str, Any]:
    """Every value the browser must reproduce, in the shape the parity test reads."""
    intervals: list[dict[str, Any]] = []
    for confidence in CONFIDENCES:
        for wells in WELL_COUNTS:
            estimable = wells >= design.MINIMUM_USEFUL_WELLS
            intervals.append(
                {
                    "wells": wells,
                    "confidence": int(round(confidence * 100)),
                    "relativeWidth": (
                        design.relative_turnover_width(wells, confidence) if estimable else None
                    ),
                    "turnoverRatio": (
                        design.turnover_ratio(wells, confidence) if estimable else None
                    ),
                }
            )

    targets = [
        {"target": target, "confidence": 95, "wells": design.wells_for_ratio(target, 0.95)}
        for target in RATIO_TARGETS
    ]

    costs: list[dict[str, Any]] = []
    for destructive in (True, False):
        assay = design.Assay(
            per_well=0.80,
            per_measurement=0.35 if destructive else 0.20,
            destructive=destructive,
            name="MTS" if destructive else "imaging",
        )
        for wells, timepoints in DESIGNS:
            plan = design.Design(
                wells=wells, times=tuple(float(index * 12) for index in range(timepoints))
            )
            costs.append(
                {
                    "wells": wells,
                    "timepoints": timepoints,
                    "destructive": destructive,
                    "wellsConsumed": plan.wells_consumed(assay),
                    "cost": plan.cost(assay),
                }
            )

    return {
        "note": (
            "Generated by scripts/generate_parity_fixtures.py from the Python "
            "package. The browser must reproduce every value. Do not edit by hand."
        ),
        "intervals": intervals,
        "wellsForRatio": targets,
        "costs": costs,
    }


def differences(
    committed: Any, fresh: Any, path: str = "$", tolerance: float = RELATIVE_TOLERANCE
) -> list[str]:
    """Every place the committed fixtures disagree with fresh ones.

    Structure, integers, flags, text and missing values must match exactly;
    floating-point values within the relative tolerance.
    """
    if isinstance(fresh, dict):
        if not isinstance(committed, dict) or sorted(committed) != sorted(fresh):
            return [f"{path}: keys differ"]
        return [
            problem
            for key in fresh
            for problem in differences(committed[key], fresh[key], f"{path}.{key}", tolerance)
        ]
    if isinstance(fresh, list):
        if not isinstance(committed, list) or len(committed) != len(fresh):
            return [f"{path}: lengths differ"]
        return [
            problem
            for index, (old, new) in enumerate(zip(committed, fresh, strict=True))
            for problem in differences(old, new, f"{path}[{index}]", tolerance)
        ]
    mismatch = [f"{path}: committed {committed!r}, fresh {fresh!r}"]
    if fresh is None or isinstance(fresh, (bool, str, int)):
        exact = committed == fresh and type(committed) is type(fresh)
        return [] if exact else mismatch
    if isinstance(committed, bool) or not isinstance(committed, (int, float)):
        return mismatch
    close = abs(committed - fresh) <= tolerance * max(abs(committed), abs(fresh))
    return [] if close else mismatch


def main(argv: list[str] | None = None) -> int:
    arguments = sys.argv[1:] if argv is None else argv
    fresh = fixtures()
    if "--check" in arguments:
        if not OUT.is_file():
            print(f"{OUT} is missing; run without --check to generate it.", file=sys.stderr)
            return 1
        problems = differences(json.loads(OUT.read_text(encoding="utf-8")), fresh)
        if problems:
            print(f"{OUT} has drifted from the package:", file=sys.stderr)
            for problem in problems[:10]:
                print(f"  {problem}", file=sys.stderr)
            return 1
        print(f"{OUT} matches the package within a relative {RELATIVE_TOLERANCE:g}")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fresh, indent=2) + "\n", encoding="utf-8")
    print(
        f"WROTE {OUT}: {len(fresh['intervals'])} intervals, "
        f"{len(fresh['wellsForRatio'])} targets, {len(fresh['costs'])} costs"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
