"""Generate the values the browser must reproduce, from the Python package.

The website reimplements TriboGuard's arithmetic so it can run without a server.
A reimplementation that drifts is worse than no demo, because both halves keep
working and quietly disagree, so these fixtures pin the two together.

Values are written at full double precision. An earlier version rounded them to
ten decimal places, which put a floor of about 1e-10 on the agreement any test
could assert -- the fixtures, not the code, were the least accurate thing in the
comparison.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from triboguard import design

OUT = Path("web/lib/__fixtures__/python-parity.json")
WELL_COUNTS = (1, 2, 3, 4, 6, 8, 12, 24, 48, 96, 200)
CONFIDENCES = (0.95, 0.90)
RATIO_TARGETS = (2.0, 3.0, 5.0, 10.0)
DESIGNS = ((3, 4), (3, 2), (12, 5), (24, 3))


def main() -> None:
    intervals: list[dict[str, Any]] = []
    for confidence in CONFIDENCES:
        for wells in WELL_COUNTS:
            estimable = wells >= design.MINIMUM_USEFUL_WELLS
            intervals.append(
                {
                    "wells": wells,
                    "confidence": int(round(confidence * 100)),
                    "relativeWidth": (
                        design.relative_turnover_width(wells, confidence) if estimable else None
                    ),
                    "turnoverRatio": (
                        design.turnover_ratio(wells, confidence) if estimable else None
                    ),
                }
            )

    targets = [
        {"target": target, "confidence": 95, "wells": design.wells_for_ratio(target, 0.95)}
        for target in RATIO_TARGETS
    ]

    costs: list[dict[str, Any]] = []
    for destructive in (True, False):
        assay = design.Assay(
            per_well=0.80,
            per_measurement=0.35 if destructive else 0.20,
            destructive=destructive,
            name="MTS" if destructive else "imaging",
        )
        for wells, timepoints in DESIGNS:
            plan = design.Design(
                wells=wells, times=tuple(float(index * 12) for index in range(timepoints))
            )
            costs.append(
                {
                    "wells": wells,
                    "timepoints": timepoints,
                    "destructive": destructive,
                    "wellsConsumed": plan.wells_consumed(assay),
                    "cost": plan.cost(assay),
                }
            )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "note": (
                    "Generated by scripts/generate_parity_fixtures.py from the Python "
                    "package. The browser must reproduce every value. Do not edit by hand."
                ),
                "intervals": intervals,
                "wellsForRatio": targets,
                "costs": costs,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"WROTE {OUT}: {len(intervals)} intervals, {len(targets)} targets, {len(costs)} costs")


if __name__ == "__main__":
    main()
